### ISSUE TITLE
Do not override servers (losing memcachier defaults)

### ISSUE THREAD

**Issue by wvengen** [liamdon/connect-memjs#3]
The current code [sets servers](https://github.com/liamdon/connect-memjs/blob/master/lib/connect-memjs.js#L56) if none are given. This breaks memjs' ability to retrieve the servers from [environment variables](https://github.com/alevy/memjs/blob/master/lib/memjs/memjs.js#L50).

Suggestion: don't provide a default, just leave servers unset when not specified.

**Comment by leohihimax** [comment]
+1 for don't provide a default. Just let memjs decide which memcached server should be used.

**Comment by liamdon** [comment]
Thanks for the nudge, just updated and published the npm module.
