### ISSUE TITLE
set call is deprecated with memjs 0.10.0

### ISSUE THREAD

**Issue by innaj** [liamdon/connect-memjs#8]
with memjs 0.10.0 I get a deprecated notification:
MemJS SET: using deprecated call - arguments have changed

just change this:

      this.client.set(sid, sess,  function() {
          fn && fn.apply(this, arguments);
      }, ttl);

to:

      this.client.set(sid, sess, {expires:ttl}, function() {
          fn && fn.apply(this, arguments);
      });

**Comment by archasek** [comment]
I'm getting ` MemJS SET: using deprecated call - arguments have changed`
